[global]
modules = ["exit_code", "cwd", "git", "prompt"]

[modules]

    [modules.exit_code]

        [modules.exit_code.style_success]
        background = "green"
        foreground = 15
        text_properties = "bold"

        [modules.exit_code.style_error]
        background = "red"
        foreground = 15
        text_properties = "bold"

    [modules.prompt]

        [modules.prompt.style_success]
        background = "green"
        foreground = 15
        text_properties = "bold"

        [modules.prompt.style_error]
        background = "red"
        foreground = 15
        text_properties = "bold"

    [modules.git]

        [modules.git.style]
        background = "cyan"
        foreground = 15

    [modules.cwd]

        [modules.cwd.style]
        background = "blue"
        foreground = 15
        
